from z3c.pagelet.browser import BrowserPagelet
from zope.app.pagetemplate.viewpagetemplatefile import ViewPageTemplateFile
from zope.publisher.browser import BrowserView

from quotationtool.biblatex import interfaces
from quotationtool.biblatex.i18n import _


class LabelView(BrowserView):
    
    def __call__(self):
        return _('bibliography-labelview',
                 u"Bibliography")


class Container(BrowserPagelet):
    """ A view that shows the contents of the bibliography."""

    def getEntries(self):
        return self.context.values()


class PlainBibtex(BrowserView):
    """A BibTeX representation of the bibliography."""

    def __call__(self):
        rc = u"%% BibLaTeX Bibliography generated by quotationtool.biblatex\n%%See http://www.quotationtool.org for more details.\n%%\n"
        rc += interfaces.IBibliographyBibtexRepresentation(self.context).getBibtex()
        return rc
