from zope.publisher.browser import BrowserView

from quotationtool.biblatex import interfaces


class PlainBibtex(BrowserView):
    """A BibTeX representation of the bibliography."""

    def __call__(self):
        rc = u"%% BibLaTeX Bibliography generated by quotationtool.biblatex\n%%See http://www.quotationtool.org for more details.\n%%\n"
        rc += interfaces.IBibliographyBibtexRepresentation(self.context).getBibtex()
        return rc
