import zope.interface
from zope.publisher.browser import BrowserView
from z3c.pagelet.browser import BrowserPagelet

from quotationtool.skin.interfaces import ITabbedContentLayout
from quotationtool.biblatex import interfaces


class HtmlBibtexEntry(BrowserPagelet):
    """A BibTeX representation of the entry embedded in the html
    layout."""

    zope.interface.implements(ITabbedContentLayout)

    def getBibtex(self):
        return interfaces.IEntryBibtexRepresentation(self.context).getBibtex()


class PlainBibtexEntry(BrowserView):
    """A plain BibTeX representation of the entry."""

    def __call__(self):
        return interfaces.IEntryBibtexRepresentation(self.context).getBibtex()


class PlainBibtexBibliography(BrowserView):
    """A BibTeX representation of the bibliography."""

    def __call__(self):
        rc = u"%% BibLaTeX Bibliography generated by quotationtool.biblatex\n%%See http://www.quotationtool.org for more details.\n%%\n"
        rc += interfaces.IBibliographyBibtexRepresentation(self.context).getBibtex()
        return rc
